export const ACTION_LOGIN = "ACTION_LOGIN";
export const ACTION_LOGOUT = "ACTION_LOGOUT";
export const ACTION_HIDE_EXPOSE = "ACTION_HIDE_EXPOSE";
export const ACTION_MARK_EXPOSE_AS_CONTACTED =
  "ACTION_MARK_EXPOSE_AS_CONTACTED";
export const ACTION_DOWNLOAD_NEW_EXPOSE = "ACTION_DOWNLOAD_NEW_EXPOSE";
export const ACTION_ADD_URL_TO_CRAWLER_LIST = "ACTION_ADD_URL_TO_CRAWLER_LIST";
export const ACTION_REMOVE_URL_FROM_CRAWLER_LIST = "ACTION_REMOVE_URL";

export const MUTATION_SET_AUTH_TOKEN = "MUTATION_SET_TOKEN";
export const MUTATION_SET_PUSH_TOKEN = "MUTATION_SET_PUSH_TOKEN";
export const MUTATION_SET_MESSAGING_ERROR = "MUTATION_SET_MESSAGING_ERROR";
export const MUTATION_SET_EXPOSE_LIST = "MUTATION_SET_EXPOSE_LIST";
export const MUTATION_ADD_EXPOSE_TO_LIST = "MUTATION_ADD_EXPOSE_TO_LIST";
export const MUTATION_UPDATE_EXPOSE_IN_LIST = "MUTATION_UPDATE_EXPOSE_IN_LIST";
export const MUTATION_CLEAR = "MUTATION_CLEAR";
export const MUTATION_SET_CRAWLER_LIST = "MUTATION_SET_CRAWLER_LIST";
export const MUTATION_ADD_URL_TO_CRAWLER_LIST =
  "MUTATION_ADD_URL_TO_CRAWLER_LIST";
export const MUTATION_REMOVE_URL_FROM_CRAWLER_LIST =
  "MUTATION_REMOVE_URL_FROM_CRAWLER_LIST";
export const MUTATION_ADD_RECEIVED_NEW_NOTIFICATION =
  "MUTATION_ADD_RECEIVED_NEW_NOTIFICATION";
export const MUTATION_REMOVE_RECEIVED_NEW_NOTIFICATION =
  "MUTATION_REMOVE_RECEIVED_NEW_NOTIFICATION";
